In [ ]:
import psycopg2

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="employee",
    user="postgres",
    password="7"
)

# Create a cursor object to interact with the database
cursor = conn.cursor()
try:
    # Create the employee table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS employees (
            id SERIAL PRIMARY KEY,
            name VARCHAR(255),
            age INTEGER,
            department VARCHAR(255),
                   
            salary DECIMAL(10, 2)
        )
    ''')

    # Insert 10 rows of employee information
    employees = [
        (1, 'John Doe', 30, 'Sales', 50000.0),
        (2, 'Jane Smith', 35, 'Marketing', 60000.0),
        (3, 'Michael Johnson', 28, 'Finance', 55000.0),
        (4, 'Emily Davis', 32, 'HR', 52000.0),
        (5, 'Robert Wilson', 40, 'Operations', 70000.0),
        (6, 'Sarah Thompson', 27, 'Sales', 48000.0),
        (7, 'David Brown', 33, 'Marketing', 58000.0),
        (8, 'Jennifer Lee', 29, 'Finance', 53000.0),
        (9, 'Christopher Martin', 31, 'HR', 51000.0),
        (10, 'Jessica Taylor', 38, 'Operations', 65000.0)
    ]

    cursor.executemany('''
        INSERT INTO employees (id, name, age, department, salary)
        VALUES (%s, %s, %s, %s, %s)
    ''', employees)

    # Commit the changes to the database
    conn.commit()

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

In [ ]:
import psycopg2
import openai

# Set your OpenAI API key
#openai.api_key = "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"
openai.api_key = "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"
# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="employee",
    user="postgres",
    password="7"
)

# Create a cursor object to interact with the database
cursor = conn.cursor()

try:
    # Fetch the table schema
    cursor.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'employees'")
    schema_rows = cursor.fetchall()
    schema = {row[0]: row[1] for row in schema_rows}

    # Generate SQL query using OpenAI
    prompt = "Generate a SQL query to retrieve data from the employees table."
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=50,
        n=1,
        stop=None,
        temperature=0.5,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0
    )
    sql_query = response.choices[0].text.strip()

    # Generate natural language question and answer using OpenAI
    prompt = "Ask a question about the employees table:\n\nQ:"
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=50,
        n=1,
        stop=None,
        temperature=0.5,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0
    )
    question = response.choices[0].text.strip()

    prompt = f"Q: {question}\n\nA:"
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=50,
        n=1,
        stop=None,
        temperature=0.5,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0
    )
    answer = response.choices[0].text.strip()

    # Print the generated SQL query, question, and answer
    print("Generated SQL Query:")
    print(sql_query)
    print("\nGenerated Question:")
    print(question)
    print("\nGenerated Answer:")
    print(answer)

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

Generated SQL Query:
SELECT * FROM employees;

Generated Question:
What is the average age of employees in the table?

Generated Answer:
The average age of employees in the table is 45.

In [12]:
import psycopg2
import openai

# Set your OpenAI API key
openai.api_key = "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"
#openai.api_key = openai.api_key = "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"
# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="employee",
    user="postgres",
    password="7"
)

# Create a cursor object to interact with the database
cursor = conn.cursor()

try:
    # Fetch the table schema
    cursor.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'employees'")
    schema_rows = cursor.fetchall()
    schema = {row[0]: row[1] for row in schema_rows}

    while True:
        # Prompt for a question or enter 'exit' to end the conversation
        question = input("Enter a question or type 'exit' to end the conversation: ")

        if question.lower() == "exit":
            break

        # Generate SQL query using OpenAI
        prompt = f"Retrieve data from the 'employees' table based on the question: {question}."
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            max_tokens=50,
            n=1,
            stop=None,
            temperature=0.5,
            top_p=1.0,
            frequency_penalty=0.0,
            presence_penalty=0.0
        )
        sql_query = response.choices[0].text.strip()

        # Execute the SQL query
        cursor.execute(sql_query)
        result = cursor.fetchall()

        # Print the question, SQL query, SQL result, and answer
        print("Question:", question)
        print("SQL Query:", sql_query)
        print("SQL Result:", result)
        print("Answer:", response.choices[0].text.strip())

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

Question: what are the toal number of employees
SQL Query: SELECT COUNT(*) FROM employees;
SQL Result: [(10,)]
Answer: SELECT COUNT(*) FROM employees;

In [7]:
import psycopg2
from psycopg2 import sql

# PostgreSQL connection details
host = "localhost"
database = "employee"
user = "postgres"
password = "7"
table_name = 'youtubevide'
csv_file = 'city_chart.csv'
# Establish a connection to the PostgreSQL database
conn = psycopg2.connect(host=host, database=database, user=user, password=password)

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Create the table if it doesn't exist
create_table_sql = """
CREATE TABLE IF NOT EXISTS {} (
    date DATE,
    city_id VARCHAR(255),
    city_name VARCHAR(255),
    views INTEGER
);
""".format(table_name)
cursor.execute(create_table_sql)

# Truncate the table if needed
cursor.execute(sql.SQL("TRUNCATE {} RESTART IDENTITY;").format(sql.Identifier(table_name)))

# Prepare the INSERT statement
insert_sql = sql.SQL("INSERT INTO {} (date, city_id, city_name, views) VALUES (%s, %s, %s, %s);").format(sql.Identifier(table_name))

# Read the CSV file and insert the data row by row
with open(csv_file, 'r') as file:
    next(file)  # Skip the header row
    for line in file:
        data = line.strip().split(',')
        cursor.execute(insert_sql, data)

# Commit the changes
conn.commit()

# Close the cursor and database connection
cursor.close()
conn.close()

print("CSV file imported successfully into the PostgreSQL table.")

CSV file imported successfully into the PostgreSQL table.

In [10]:
import psycopg2
import openai

# Set your OpenAI API key
openai.api_key = "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"
#openai.api_key = openai.api_key = "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"
# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="employee",
    user="postgres",
    password="7"
)

# Create a cursor object to interact with the database
cursor = conn.cursor()

try:
    # Fetch the table schema
    cursor.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'youtubevide'")
    schema_rows = cursor.fetchall()
    schema = {row[0]: row[1] for row in schema_rows}

    while True:
        # Prompt for a question or enter 'exit' to end the conversation
        question = input("Enter a question or type 'exit' to end the conversation: ")

        if question.lower() == "exit":
            break

        # Generate SQL query using OpenAI
        prompt = f"Retrieve data from the 'youtubevide' table based on the question: {question}."
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            max_tokens=50,
            n=1,
            stop=None,
            temperature=0.5,
            top_p=1.0,
            frequency_penalty=0.0,
            presence_penalty=0.0
        )
        sql_query = response.choices[0].text.strip()

        # Execute the SQL query
        cursor.execute(sql_query)
        result = cursor.fetchall()

        # Print the question, SQL query, SQL result, and answer
        print("Question:", question)
        print("SQL Query:", sql_query)
        print("SQL Result:", result)
        print("Answer:", response.choices[0].text.strip())

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

Question: swhat about total number who  city_name  is  Addis Ababa
SQL Query: SELECT COUNT(*)
FROM youtubevide
WHERE city_name = 'Addis Ababa';
SQL Result: [(1279,)]
Answer: SELECT COUNT(*)
FROM youtubevide
WHERE city_name = 'Addis Ababa';

UndefinedTable: relation "youtubevideo" does not exist
LINE 1: SELECT COUNT(*) FROM youtubevideo WHERE city_name = 'Addis A...
                             ^

In [ ]:
city_name  | views 
------------+---------------------------------------+-------------+-------
 2020-06-28 | 0x164b85cef5ab402d:0x8467b6b037a24d49 | Addis Ababa